name: Hello Workflow

on: 
  push:
    branches:
      - master   # Trigger on push to master branch

jobs:
  hello:                    
    runs-on: ubuntu-latest  
    steps:
      - name: Say Hello
        run: echo "Hello GitHub Actions!"

      - name: Current date
        run: echo "date is 17th October"
