name: "Multievent pipeline"
on:
    push:
        branches:
            - master
            - test
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    on-push:
        if: github.event_name == 'push' #checks or conditions
        runs-on: ubuntu-latest
        steps:
            - name: "pushing on master branch"
              run: echo "Running on master branch"
    
    on-pull_request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "running on pull request"       